version: "3.8"
services:
  install:
    build: 
      context: .
    image: install
    volumes:
      - ${HOSTINSTALLPATH}:/starbound
    environment:
      - STEAMUSER=${STEAMUSER}
      - STEAMPASSWORD=${STEAMPASSWORD}
    entrypoint: ./update_starbound_server.sh
    command: ${STEAMGUARD}

  server:
    build:
      context: .
    volumes:
      - ${HOSTINSTALLPATH}:/starbound
    command: ./starbound_server
    working_dir: /starbound/linux
    ports:
      - 21025:21025
        #stdin_open: true # docker run -i
        #tty: true        # docker run -t



