version: "3.8"
services:
  install:
    build: 
      context: .
    image: install
    volumes:
      - ./starbound:/starbound
    stdin_open: true # docker run -i
    tty: true        # docker run -t

