version: "3.8"
services:
  install:
    build: 
      context: .
    image: install
    volumes:
      - ${HOSTINSTALLPATH}:/starbound
    environment:
      - STEAMUSER=${STEAMUSER}
      - STEAMPASSWORD=${STEAMPASSWORD}
      - STEAMGUARD=${STEAMGUARD}
      - STARBOUNDPATH=${STARBOUNDPATH}
    command: ./update_starbound_server.sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  server:
    image: install
    volumes:
      - ${HOSTINSTALLPATH}:/starbound
    environment:
      - STARBOUNDPATH=${STARBOUNDPATH}
    command: bash ${STARBOUNDPATH}/linux/starbound_server.sh
    ports:
      - 21025:21025
 

